### PR TITLE
Heroku setup

### PR DESCRIPTION
**Pull request by kevinweaver**
## Problem
We need this on heroku with a root page

## Solution
Create the root page

### CODE REVIEW

**Comment by carmensea** [comment]
@kevinweaver I don't see how you're solving this problem? Is there a better way, perhaps?

**Comment by kevinweaver** [comment]
I'm 100% sure there is a better way to solve this problem.  Wix and Squarespace to name a few.  But that would be too easy.

**Comment by kevinweaver** [comment]
@carmensea I'm going to wrastle you.

**Comment by kevinweaver** [comment]
https://weavers-web.herokuapp.com/

**Pull request merged**
